### ISSUE TITLE
There should be a way of gracefully handling duplicate-prefix errrors

### ISSUE THREAD

**Issue by ont-app** [ont-app/vocabulary#9]
A `:voc/DuplicatePrefix,` error is thrown when the same prefix is mapped to more than one namespace. This can be inconvenient for users downstream.

There should be a hook or something we can define downstream that resolves such ambiguities.

**Comment by simongray** [comment]
So since you asked for feedback about this library, I was heading over to report this issue only to find that you already did so yourself 😄 

The library automatically registers a selection of prefixes - which is nice if you assume that these prefixes are universally thought to refer to whatever `ont-app/vocabulary` thinks they mean... I guess they would be in most cases. Now, since this is done implicitly when loading the namespace, it seems like the default behaviour should be to **overwrite** existing prefixes if you attempt to register something that will create conflicts within the existing prefix cache.

Either that, or make the loading of these built-in prefixes explicit, e.g. through a function call or by reguiring the library consumer to load a separate namespace than `ont-app.vocabulary.core` so that it may be opt-in instead.

IMO a good user experience would be to always provide a warning when something is overwritten. You currently have no idea that the prefix cache is invalid until you attempt to do something with a graph, but this knowledge is actually present at the time that you call `(voc/put-ns-meta! ...)`. Better to fail fast then! 💪

**Comment by ericdscott** [comment]
This appears to have been fixed with 628c169, which introduces an 'on-duplicate-prefix' which can be overridden with `with-redefs` as needed.

**Comment by simongray** [comment]
Nice! And thanks for putting out version 0.1.7 so fast too. Another TODO off my list :-)
